// import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import PreBanner from "./components/PreBanner";
import Footer from "./components/Footer";
import Banner from "./components/Banner";
import SubFooter from "./components/SubFooter";
import Contact from "./components/Contact";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PreBanner message="" created_at={new Date()} />
        <Banner />
        <Contact email="example@example.com" phone="123-456-7890" />
        {children}
        <Contact email="example@example.com" phone="123-456-7890" />
        <Footer />
        <SubFooter />
      </body>
    </html>
  );
}
